<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreTransactionDetRequest extends FormRequest
{
    public function authorize()
    {
        return true;
    }

    public function rules()
    {
        return [
            'Idx'   => 'unique:transaction_dets,Idx',
            'ProductID'          => 'nullable',
            'ProductCode'        => 'nullable|max:25',
            'RefCode'            => 'nullable|max:25',
            'BarCodeFull'        => 'nullable',
            'Descrip'            => 'nullable|max:50',
            'BatchNo'            => 'nullable|max:50',
            'SerialNo'           => 'nullable|max:50',
            'ExpiaryDate'        => 'nullable',
            'Cost'               => 'nullable',
            'AvgCost'            => 'nullable',
            'Price'              => 'nullable',
            'Qty'                => 'nullable',
            'Amount'             => 'nullable',
            'UnitOfMeasureID'    => 'nullable',
            'UnitOfMeasureName'  => 'nullable|max:10',
            'ConvertFactor'      => 'nullable',
            'IDI1'               => 'nullable',
            'IDis1'              => 'nullable',
            'IDiscount1'         => 'nullable',
            'IDI1CashierID'      => 'nullable',
            'IDI2'               => 'nullable',
            'IDis2'              => 'nullable',
            'IDiscount2'         => 'nullable',
            'IDI2CashierID'      => 'nullable',
            'IDI3'               => 'nullable',
            'IDis3'              => 'nullable',
            'IDiscount3'         => 'nullable',
            'IDI3CashierID'      => 'nullable',
            'IDI4'               => 'nullable',
            'IDis4'              => 'nullable',
            'IDiscount4'         => 'nullable',
            'IDI4CashierID'      => 'nullable',
            'IDI5'               => 'nullable',
            'IDis5'              => 'nullable',
            'IDiscount5'         => 'nullable',
            'IDI5CashierID'      => 'nullable',
            'Rate'               => 'nullable',
            'IsSDis'             => 'nullable',
            'SDNo'               => 'nullable',
            'SDID'               => 'nullable',
            'SDIs'               => 'nullable',
            'SDiscount'          => 'nullable',
            'DDisCashierID'      => 'nullable',
            'Nett'               => 'nullable',
            'LocationID'         => 'nullable',
            'DocumentID'         => 'nullable',
            'BillTypeID'         => 'nullable',
            'SaleTypeID'         => 'nullable',
            'Receipt'            => 'nullable|max:10',
            'SalesmanID'         => 'nullable',
            'Salesman'           => 'nullable|max:15',
            'CustomerID'         => 'nullable',
            'Customer'           => 'nullable|max:150',
            'CashierID'          => 'nullable',
            'Cashier'            => 'nullable|max:15',
            'StartTime'          => 'nullable',
            'EndTime'            => 'nullable',
            'RecDate'            => 'nullable',
            'BaseUnitID'         => 'nullable',
            'UnitNo'             => 'nullable',
            'RowNo'              => 'nullable',
            'IsRecall'           => 'nullable',
            'RecallNo'           => 'nullable|max:10',
            'RecallAdv'          => 'nullable',
            'TaxAmount'          => 'nullable',
            'IsTax'              => 'nullable',
            'TaxPercentage'      => 'nullable',
            'IsStock'            => 'nullable',
            'UpdateBy'           => 'nullable',
            'Status'             => 'nullable',
            'CustomerType'       => 'nullable',
            'ZNo'                => 'nullable',
            'TransStatus'        => 'nullable',
            'IsPromotionApplied' => 'nullable',
            'PromotionID'        => 'nullable',
            'IsPromotion'        => 'nullable',
            'LocationIDBilling'  => 'nullable',
            'TableID'            => 'nullable',
            'OrderTerminalID'    => 'nullable',
            'TicketID'           => 'nullable',
            'OrderNo'            => 'nullable',
            'IsPrinted'          => 'nullable',
            'ItemComment'        => 'nullable|max:100',
            'Packs'              => 'nullable',
            'IsCancelKOT'        => 'nullable',
            'StewardID'          => 'nullable',
            'StewardName'        => 'nullable|max:50',
            'ServiceCharge'      => 'nullable',
            'ServiceChargeAmount'=> 'nullable',
            'ShiftNo'            => 'nullable',
            'IsDayEnd'           => 'nullable',
            'UpdateUnitNo'       => 'nullable',
            'ZDate'              => 'nullable',
            'TagNo'              => 'nullable|max:50',
        ];
    }

    public function attributes()
    {
        return [
            'Idx'   => 'transaction detail ID',
            'ProductID'          => 'product ID',
            'ProductCode'        => 'product code',
            'RefCode'            => 'reference code',
            'BarCodeFull'        => 'full barcode',
            'ExpiaryDate'        => 'expiry date',
            'UnitOfMeasureID'    => 'unit of measure ID',
            'UnitOfMeasureName'  => 'unit of measure name',
            'ConvertFactor'      => 'convert factor',
            'SalesmanID'         => 'salesman ID',
            'CustomerID'         => 'customer ID',
            'CashierID'          => 'cashier ID',
            'StartTime'          => 'start time',
            'EndTime'            => 'end time',
            'RecDate'            => 'receipt date',
            'BaseUnitID'         => 'base unit ID',
            'UnitNo'             => 'unit number',
            'RowNo'              => 'row number',
            'RecallNo'           => 'recall number',
            'TaxAmount'          => 'tax amount',
            'TaxPercentage'      => 'tax percentage',
            'UpdateBy'           => 'updated by',
            'CustomerType'       => 'customer type',
            'TransStatus'        => 'transaction status',
            'PromotionID'        => 'promotion ID',
            'LocationIDBilling'  => 'billing location ID',
            'TableID'            => 'table ID',
            'OrderTerminalID'    => 'order terminal ID',
            'TicketID'           => 'ticket ID',
            'OrderNo'            => 'order number',
            'ItemComment'        => 'item comment',
            'StewardID'          => 'steward ID',
            'StewardName'        => 'steward name',
            'ServiceCharge'      => 'service charge',
            'ServiceChargeAmount'=> 'service charge amount',
            'ShiftNo'            => 'shift number',
            'UpdateUnitNo'       => 'update unit number',
            'ZDate'              => 'Z date',
            'TagNo'              => 'tag number',
        ];
    }
}
