<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TransactionDet extends Model
{
    /** @use HasFactory<\Database\Factories\TransactionDetFactory> */
    use HasFactory;

    protected $fillable = [
        'Idx',
        'ProductID',
        'ProductCode',
        'RefCode',
        'BarCodeFull',
        'Descrip',
        'BatchNo',
        'SerialNo',
        'ExpiaryDate',
        'Cost',
        'AvgCost',
        'Price',
        'Qty',
        'Amount',
        'UnitOfMeasureID',
        'UnitOfMeasureName',
        'ConvertFactor',
        'IDI1',
        'IDis1',
        'IDiscount1',
        'IDI1CashierID',
        'IDI2',
        'IDis2',
        'IDiscount2',
        'IDI2CashierID',
        'IDI3',
        'IDis3',
        'IDiscount3',
        'IDI3CashierID',
        'IDI4',
        'IDis4',
        'IDiscount4',
        'IDI4CashierID',
        'IDI5',
        'IDis5',
        'IDiscount5',
        'IDI5CashierID',
        'Rate',
        'IsSDis',
        'SDNo',
        'SDID',
        'SDIs',
        'SDiscount',
        'DDisCashierID',
        'Nett',
        'LocationID',
        'DocumentID',
        'BillTypeID',
        'SaleTypeID',
        'Receipt',
        'SalesmanID',
        'Salesman',
        'CustomerID',
        'Customer',
        'CashierID',
        'Cashier',
        'StartTime',
        'EndTime',
        'RecDate',
        'BaseUnitID',
        'UnitNo',
        'RowNo',
        'IsRecall',
        'RecallNo',
        'RecallAdv',
        'TaxAmount',
        'IsTax',
        'TaxPercentage',
        'IsStock',
        'UpdateBy',
        'Status',
        'CustomerType',
        'ZNo',
        'TransStatus',
        'IsPromotionApplied',
        'PromotionID',
        'IsPromotion',
        'LocationIDBilling',
        'TableID',
        'OrderTerminalID',
        'TicketID',
        'OrderNo',
        'IsPrinted',
        'ItemComment',
        'Packs',
        'IsCancelKOT',
        'StewardID',
        'StewardName',
        'ServiceCharge',
        'ServiceChargeAmount',
        'ShiftNo',
        'IsDayEnd',
        'UpdateUnitNo',
        'ZDate',
        'TagNo',
    ];
}
